name: Backend Compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile Spring Boot Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile Backend with Maven
        run: mvn clean compile
