package com.project.back_end.services;

import java.util.HashMap;
import java.util.Map;

import javax.crypto.SecretKey;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service; 
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.security.Keys;
import io.jsonwebtoken.security.SignatureException;

@Service
public class TokenService {
	
	 // Spring injects the property value directly into this variable string
    @Value("${jwt.secret}")
    private String secretKey;
// 1. **@Component Annotation**
// The @Component annotation marks this class as a Spring component, meaning Spring will manage it as a bean within its application context.
// This allows the class to be injected into other Spring-managed components (like services or controllers) where it's needed.

// 2. **Constructor Injection for Dependencies**
// The constructor injects dependencies for `AdminRepository`, `DoctorRepository`, and `PatientRepository`,
// allowing the service to interact with the database and validate users based on their role (admin, doctor, or patient).
// Constructor injection ensures that the class is initialized with all required dependencies, promoting immutability and making the class testable.

// 3. **getSigningKey Method**
// This method retrieves the HMAC SHA key used to sign JWT tokens.
// It uses the `jwt.secret` value, which is provided from an external source (like application properties).
// The `Keys.hmacShaKeyFor()` method converts the secret key string into a valid `SecretKey` for signing and verification of JWTs.

// 4. **generateToken Method**
// This method generates a JWT token for a user based on their email.
// - The `subject` of the token is set to the user's email, which is used as an identifier.
// - The `issuedAt` is set to the current date and time.
// - The `expiration` is set to 7 days from the issue date, ensuring the token expires after one week.
// - The token is signed using the signing key generated by `getSigningKey()`, making it secure and tamper-proof.
// The method returns the JWT token as a string.

// 5. **extractEmail Method**
// This method extracts the user's email (subject) from the provided JWT token.
// - The token is first verified using the signing key to ensure it hasn’t been tampered with.
// - After verification, the token is parsed, and the subject (which represents the email) is extracted.
// This method allows the application to retrieve the user's identity (email) from the token for further use.

// 6. **validateToken Method**
// This method validates whether a provided JWT token is valid for a specific user role (admin, doctor, or patient).
// - It first extracts the email from the token using the `extractEmail()` method.
// - Depending on the role (`admin`, `doctor`, or `patient`), it checks the corresponding repository (AdminRepository, DoctorRepository, or PatientRepository)
//   to see if a user with the extracted email exists.
// - If a match is found for the specified user role, it returns true, indicating the token is valid.
// - If the role or user does not exist, it returns false, indicating the token is invalid.
// - The method gracefully handles any errors by returning false if the token is invalid or an exception occurs.
// This ensures secure access control based on the user's role and their existence in the system.
	// Conceptual preview of the future validation enhancement loop
  

    public Map<String, Object> validateToken(String token, String expectedRole) {
        Map<String, Object> response = new HashMap<>();
        
        try {
            // 1. Convert the plain text secret string into a cryptographic SecretKey object
            SecretKey key = Keys.hmacShaKeyFor(this.secretKey.getBytes());

            // 2. Safely parse and verify the JWT using the updated, modern immutable chain
            Claims claims = Jwts.parser()
                                .verifyWith(key)
                                .build()
                                .parseSignedClaims(token)
                                .getPayload();

            // 3. Extract and check the role from the claims to ensure authorization matches
            String role = claims.get("role", String.class);
            
            if (role == null || !role.equalsIgnoreCase(expectedRole)) {
                response.put("status", "error");
                response.put("message", "Unauthorized access: Missing or mismatching role mapping.");
                return response;
            }

            // Token is completely valid and matching roles confirmed
            response.put("status", "success");
            response.put("claims", claims);
            response.put("username", claims.getSubject());
            
        } catch (ExpiredJwtException e) {
            response.put("status", "error");
            response.put("message", "Token validation failed: The provided token has expired.");
        } catch (MalformedJwtException | IllegalArgumentException e) {
            response.put("status", "error");
            response.put("message", "Token validation failed: The token format is structural invalid.");
        } catch (SignatureException e) {
            response.put("status", "error");
            response.put("message", "Token validation failed: Cryptographic signature mismatch or manipulation detected.");
        } catch (Exception e) {
            response.put("status", "error");
            response.put("message", "Token validation failed due to an unexpected system exception: " + e.getMessage());
        }

        return response;
    }

}


