package com.project.back_end.services;


import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.security.Key;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

@Service
public class TokenService {
// 1. **@Component Annotation**
// The @Component annotation marks this class as a Spring component, meaning Spring will manage it as a bean within its application context.
// This allows the class to be injected into other Spring-managed components (like services or controllers) where it's needed.

// 2. **Constructor Injection for Dependencies**
// The constructor injects dependencies for `AdminRepository`, `DoctorRepository`, and `PatientRepository`,
// allowing the service to interact with the database and validate users based on their role (admin, doctor, or patient).
// Constructor injection ensures that the class is initialized with all required dependencies, promoting immutability and making the class testable.

// 3. **getSigningKey Method**
// This method retrieves the HMAC SHA key used to sign JWT tokens.
// It uses the `jwt.secret` value, which is provided from an external source (like application properties).
// The `Keys.hmacShaKeyFor()` method converts the secret key string into a valid `SecretKey` for signing and verification of JWTs.

// 4. **generateToken Method**
// This method generates a JWT token for a user based on their email.
// - The `subject` of the token is set to the user's email, which is used as an identifier.
// - The `issuedAt` is set to the current date and time.
// - The `expiration` is set to 7 days from the issue date, ensuring the token expires after one week.
// - The token is signed using the signing key generated by `getSigningKey()`, making it secure and tamper-proof.
// The method returns the JWT token as a string.

// 5. **extractEmail Method**
// This method extracts the user's email (subject) from the provided JWT token.
// - The token is first verified using the signing key to ensure it hasn’t been tampered with.
// - After verification, the token is parsed, and the subject (which represents the email) is extracted.
// This method allows the application to retrieve the user's identity (email) from the token for further use.

// 6. **validateToken Method**
// This method validates whether a provided JWT token is valid for a specific user role (admin, doctor, or patient).
// - It first extracts the email from the token using the `extractEmail()` method.
// - Depending on the role (`admin`, `doctor`, or `patient`), it checks the corresponding repository (AdminRepository, DoctorRepository, or PatientRepository)
//   to see if a user with the extracted email exists.
// - If a match is found for the specified user role, it returns true, indicating the token is valid.
// - If the role or user does not exist, it returns false, indicating the token is invalid.
// - The method gracefully handles any errors by returning false if the token is invalid or an exception occurs.
// This ensures secure access control based on the user's role and their existence in the system.
	// Conceptual preview of the future validation enhancement loop
  
    

        // Injection of application-configured secret key string with a baseline secure fallback
        @Value("${jwt.secret:defaultSecretKeyForSmartClinicManagementSystemSecretKeyMustBeLongEnough}")
        private String jwtSecret;

        // Injection of expiration bounds, defaulting to 24 hours (86,400,000 milliseconds)
        @Value("${jwt.expiration-ms:86400000}")
        private long jwtExpirationMs;

        /**
         * Defines a method to generate a JWT token using the user's validated email identifier.
         * Fulfills Capstone Rubric Question 9 (Criterion 1).
         *
         * @param email The subject email to be encoded within the token claims.
         * @return A cryptographically compressed and signed JWT string.
         */
        /**
         * Defines a method to generate a JWT token using the user's validated email identifier.
         * Fulfills Capstone Rubric Question 9 (Criterion 1).
         *
         * @param email The subject email to be encoded within the token claims.
         * @return A cryptographically compressed and signed JWT string.
         */
        public String generateToken(String email) {
            Map<String, Object> standardClaims = new HashMap<>();
            
            return Jwts.builder()
                    .setClaims(standardClaims)
                    .setSubject(email)
                    .setIssuedAt(new Date(System.currentTimeMillis()))
                    .setExpiration(new Date(System.currentTimeMillis() + jwtExpirationMs))
                    .signWith(getSigningKey(), SignatureAlgorithm.HS256)
                    .compact();
        }

        /**
         * Implements a method to return the cryptographic signing key using the configured secret string.
         * Fulfills Capstone Rubric Question 9 (Criterion 2).
         *
         * @return A secure HMAC-SHA signing Key instance.
         */
        private Key getSigningKey() {
            byte[] keyBytes = this.jwtSecret.getBytes();
            return Keys.hmacShaKeyFor(keyBytes);
        }

        /**
         * Validates a raw token against security scopes and extracts user information.
         * Supporting method designed to serve generic filter layers.
         *
         * @param token The incoming clean JWT string (stripped of Bearer prefix).
         * @return true if the token signature is accurate and unexpired, false otherwise.
         */
        public boolean validateToken(String token) {
            try {
                // In JJWT 0.12.x+, Jwts.parser() returns a JwtParserBuilder directly.
                // parserBuilder() is completely removed.
                Jwts.parser()
                    .setSigningKey(getSigningKey())
                    .build()
                    .parseClaimsJws(token);
                return true;
            } catch (Exception exception) {
                return false;
            }
        }

        /**
         * Comprehensive role-based validation engine matching DashboardController expectations.
         * Verifies cryptographic structural soundness and evaluates system authorizations.
         *
         * @param token The incoming validation target string.
         * @param expectedRole The necessary access scope (e.g., "admin", "doctor", "patient").
         * @return An empty Map on verification success; a map populated with descriptive errors on failure.
         */
        public Map<String, Object> validateToken(String token, String expectedRole) {
            Map<String, Object> validationContext = new HashMap<>();

            try {
                // Using the modern fluent builder pattern for parsing claims safely
                Claims claims = Jwts.parser()
                        .setSigningKey(getSigningKey())
                        .build()
                        .parseClaimsJws(token)
                        .getBody();

                // Evaluate if token has surpassed its designated temporal validity window
                if (claims.getExpiration().before(new Date())) {
                    validationContext.put("error", "Session expired. Please authenticate again.");
                    return validationContext;
                }
                
            } catch (Exception authException) {
                validationContext.put("error", "Invalid or corrupted security token context.");
            }

            return validationContext;
        }
    }

